library(retistruct)
dataset <- file.path(system.file(package = "retistruct"), "extdata", "GM114-4-RC")
r <- retistruct.read.dataset(dataset)
r <- retistruct.read.recdata(r)
print(getDss.mean(r))
Dss <- getDss(r)
Sss <- getSss(r)
Ims <- getIms(r)
